-- MySQL Script generated by MySQL Workbench
-- Tue Oct 10 22:31:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

create schema TGP;


use TGP;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` BIGINT(100) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Funcionario` (
  `idFuncionario` BIGINT(100) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `NomeArtistico` VARCHAR(45) NOT NULL,
  `NomeReal` VARCHAR(45) NOT NULL,
  `Funcao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Produto` (
  `idProduto` BIGINT(100) NOT NULL,
  `GTIN` DOUBLE NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NULL,
  `Conteudo` VARCHAR(2) NOT NULL,
  `Valor` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Servico` (
  `idServico` BIGINT(100) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Valor` DECIMAL(12,2) NOT NULL,
  `Funcionario_idFuncionario1` BIGINT(100) NOT NULL,
  PRIMARY KEY (`idServico`),
  INDEX `fk_Servico_Funcionario1_idx` (`Funcionario_idFuncionario1` ASC),
  CONSTRAINT `fk_Servico_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario1`)
    REFERENCES `Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido` (
  `idPedido` BIGINT(100) NOT NULL,
  `Data` DATETIME NOT NULL,
  `ValorTotal` DECIMAL(12,2) NOT NULL,
  `Cliente_idCliente1` BIGINT(100) NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente1` ASC),
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente1`)
    REFERENCES `Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido_has_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_has_Produto` (
  `Pedido_idPedido` BIGINT(100) NOT NULL,
  `Produto_idProduto` BIGINT(100) NOT NULL,
  `Quantidade` FLOAT NOT NULL,
  `Valor_produto` DECIMAL(12,2) NOT NULL,
  `Valor_total_produto` DECIMAL(12,2) NOT NULL,
  `idPedido_has_Produtocol` BIGINT(100) NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Produto_idProduto`, `idPedido_has_Produtocol`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Pedido_has_Produto_Pedido_idx` (`Pedido_idPedido` ASC),
  CONSTRAINT `fk_Pedido_has_Produto_Pedido`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedido_has_Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido_has_Servico` (
  `Pedido_idPedido` BIGINT(100) NOT NULL,
  `Servico_idServico` BIGINT(100) NOT NULL,
  `Quantidade` FLOAT NOT NULL,
  `Valor_servico` DECIMAL(12,2) NOT NULL,
  `Valor_total_servico` DECIMAL(12,2) NOT NULL,
  `idPedido_has_Servicocol` BIGINT(100) NOT NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Servico_idServico`, `idPedido_has_Servicocol`),
  INDEX `fk_Pedido_has_Servico_Servico1_idx` (`Servico_idServico` ASC),
  INDEX `fk_Pedido_has_Servico_Pedido1_idx` (`Pedido_idPedido` ASC),
  CONSTRAINT `fk_Pedido_has_Servico_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Servico_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
